name: anima_pos_inapp
description: ANIMA POS with in-app Supabase setup
publish_to: "none"
version: 0.2.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.5.6
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  uuid: ^4.4.2
  path: ^1.9.0
  sqflite: ^2.3.3
  path_provider: ^2.1.4
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
